/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tttHookSol from "./TTTHook.sol";
export type { tttHookSol };
export type { PoolHelper } from "./PoolHelper";
export type { ProtocolFee } from "./ProtocolFee";
export type { TTT } from "./TTT";
export type { TTTHookSimple } from "./TTTHookSimple";
export type { TTTToken } from "./TTTToken";
export type { TestTTT } from "./TestTTT";
