/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  LPFeeLibrary,
  LPFeeLibraryInterface,
} from "../../../../../@uniswap/v4-core/src/libraries/LPFeeLibrary";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint24",
        name: "fee",
        type: "uint24",
      },
    ],
    name: "LPFeeTooLarge",
    type: "error",
  },
  {
    inputs: [],
    name: "DYNAMIC_FEE_FLAG",
    outputs: [
      {
        internalType: "uint24",
        name: "",
        type: "uint24",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_LP_FEE",
    outputs: [
      {
        internalType: "uint24",
        name: "",
        type: "uint24",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "OVERRIDE_FEE_FLAG",
    outputs: [
      {
        internalType: "uint24",
        name: "",
        type: "uint24",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "REMOVE_OVERRIDE_MASK",
    outputs: [
      {
        internalType: "uint24",
        name: "",
        type: "uint24",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60c66032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106050575f3560e01c80633b01d64d1460545780633fc48eba1460755780636f95ebcf14607e578063f26ef49d146087575b5f5ffd5b605d6240000081565b60405162ffffff909116815260200160405180910390f35b605d620f424081565b605d62bfffff81565b605d628000008156fea2646970667358221220a1ede31d48fa4b7f778253f5812f2cbc0383a1873b196f99e3928254da93b0ee64736f6c634300081b0033";

type LPFeeLibraryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: LPFeeLibraryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class LPFeeLibrary__factory extends ContractFactory {
  constructor(...args: LPFeeLibraryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      LPFeeLibrary & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): LPFeeLibrary__factory {
    return super.connect(runner) as LPFeeLibrary__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LPFeeLibraryInterface {
    return new Interface(_abi) as LPFeeLibraryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): LPFeeLibrary {
    return new Contract(address, _abi, runner) as unknown as LPFeeLibrary;
  }
}
