/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../../common";
import type {
  BalanceDeltaLibrary,
  BalanceDeltaLibraryInterface,
} from "../../../../../../@uniswap/v4-core/src/types/BalanceDelta.sol/BalanceDeltaLibrary";

const _abi = [
  {
    inputs: [],
    name: "ZERO_DELTA",
    outputs: [
      {
        internalType: "BalanceDelta",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60846032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106032575f3560e01c806391cb4669146036575b5f5ffd5b603c5f81565b60405190815260200160405180910390f3fea26469706673582212208c7fd2c415f85876fa147351093add9ae01f8e2192423c2070fbd6b66f49bbaf64736f6c634300081b0033";

type BalanceDeltaLibraryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BalanceDeltaLibraryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BalanceDeltaLibrary__factory extends ContractFactory {
  constructor(...args: BalanceDeltaLibraryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      BalanceDeltaLibrary & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): BalanceDeltaLibrary__factory {
    return super.connect(runner) as BalanceDeltaLibrary__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BalanceDeltaLibraryInterface {
    return new Interface(_abi) as BalanceDeltaLibraryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): BalanceDeltaLibrary {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as BalanceDeltaLibrary;
  }
}
