/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { ITTT, ITTTInterface } from "../../../contracts/TTTHook.sol/ITTT";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "stratum",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "grgHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "potHash",
        type: "bytes32",
      },
    ],
    name: "anchorPoT",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITTT__factory {
  static readonly abi = _abi;
  static createInterface(): ITTTInterface {
    return new Interface(_abi) as ITTTInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ITTT {
    return new Contract(address, _abi, runner) as unknown as ITTT;
  }
}
